### ISSUE TITLE
Scripted extension instead of startup script

### ISSUE THREAD

**Issue by bjorn** [ilius33/TiledToAngbandExport#1]
To ease installation of scripts I've added support for [scripted extensions](https://doc.mapeditor.org/en/latest/reference/scripting/#scripted-extensions). The main difference is that there isn't just one script executed on startup, but multiple extensions can be added to the user's extensions path to be loaded on startup.

Currently (as of snapshot 2019.10.08) each extension needs its own directory, though I think this adds a rather unnecessary hurdle for "single .js file" extensions. So in the end I may opt to also load any .js file placed directly in the extensions folder.

**Comment by ilius33** [comment]
Made little changes to work better with new scripted extensions feature.
