### ISSUE TITLE
Adjustments needed for Tiled 1.3

### ISSUE THREAD

**Issue by bjorn** [ilius33/TiledToAngbandExport#3]
Before the final Tiled 1.3.0 release I've ended up changing the API for custom formats, due to the support for writing both text and binary files as well as to support writing to multiple files. This means you can no longer just return the string you'd like to save to the target file.

Instead, you need to write the string to the file explicitly at the end of the `write` function:

```js
var file = new TextFile(fileName, TextFile.WriteOnly);
file.write(asciiMap);
file.commit();
```

**Comment by ilius33** [comment]
Thanks for the update. Made a quick commit.
